// src/App.svelte
<script>
  import { onMount } from "svelte";
  import fallbackLogo from "./assets/logo-fallback.svg";
  import { fetchArticlesBySource, fetchAllSources } from "./api";

  let isSidebarOpen = $state(false);
  let searchQuery = $state("");
  let visibleCount = $state({});
  let currentSlide = $state(0);
  let sliderColors = $state([]);
  let cardColors = $state([]);
  let featuredNews = $state([]);
  let newsSources = $state([]);
  let isLoading = $state(true);
  let loadingMore = $state({});

  // Fungsi untuk shuffle array
  function shuffleArray(array) {
    const shuffled = [...array];
    for (let i = shuffled.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
    }
    return shuffled;
  }

  // All colors
  const allSliderColors = [
    "bg-gradient-to-br from-pink-400 via-purple-400 to-indigo-500",
    "bg-gradient-to-br from-yellow-400 via-orange-400 to-red-500",
    "bg-gradient-to-br from-green-400 via-emerald-400 to-teal-500",
    "bg-gradient-to-br from-blue-400 via-cyan-400 to-sky-500",
    "bg-gradient-to-br from-violet-400 via-fuchsia-400 to-pink-500",
    "bg-gradient-to-br from-amber-400 via-lime-400 to-green-500",
    "bg-gradient-to-br from-red-400 via-rose-400 to-pink-500",
    "bg-gradient-to-br from-cyan-400 via-blue-400 to-indigo-500",
    "bg-gradient-to-br from-lime-400 via-green-400 to-emerald-500",
    "bg-gradient-to-br from-orange-400 via-amber-400 to-yellow-500",
    "bg-gradient-to-br from-fuchsia-400 via-purple-400 to-violet-500",
    "bg-gradient-to-br from-teal-400 via-cyan-400 to-blue-500",
  ];

  const allCardColors = [
    "bg-pink-100",
    "bg-yellow-100",
    "bg-green-100",
    "bg-blue-100",
    "bg-purple-100",
    "bg-orange-100",
    "bg-teal-100",
    "bg-indigo-100",
    "bg-rose-100",
    "bg-lime-100",
    "bg-cyan-100",
    "bg-amber-100",
    "bg-emerald-100",
    "bg-sky-100",
    "bg-violet-100",
    "bg-fuchsia-100",
    "bg-red-100",
    "bg-slate-100",
    "bg-stone-100",
    "bg-zinc-100",
  ];

  // Body background colors (subtle patterns)
  const allBodyBackgrounds = [
    "bg-gradient-to-br from-pink-200 via-purple-100 to-purple-200",
    "bg-gradient-to-br from-yellow-200 via-orange-100 to-orange-200",
    "bg-gradient-to-br from-green-200 via-emerald-100 to-emerald-200",
    "bg-gradient-to-br from-blue-200 via-cyan-100 to-cyan-200",
    "bg-gradient-to-br from-purple-200 via-fuchsia-100 to-fuchsia-200",
    "bg-gradient-to-br from-orange-200 via-amber-100 to-amber-200",
    "bg-gradient-to-br from-teal-200 via-cyan-100 to-cyan-200",
    "bg-gradient-to-br from-indigo-200 via-blue-100 to-blue-200",
    "bg-gradient-to-br from-rose-200 via-pink-100 to-pink-200",
    "bg-gradient-to-br from-lime-200 via-green-100 to-green-200",
  ];

  // Initialize colors on mount
  sliderColors = shuffleArray(allSliderColors);
  cardColors = shuffleArray(allCardColors);
  let bodyBgColor = $state(allBodyBackgrounds[Math.floor(Math.random() * allBodyBackgrounds.length)]);
  $effect(() => {
    bodyBgColor = allBodyBackgrounds[Math.floor(Math.random() * allBodyBackgrounds.length)];
  });

  // Load initial articles from backend API
  async function loadInitialArticles() {
    isLoading = true;
    try {
      // Fetch all sources first
      const sourcesData = await fetchAllSources();
      
      // Then fetch articles for each source
      const results = await Promise.all(
        sourcesData.sources.map(async (source) => {
          const data = await fetchArticlesBySource(source.id, 11); // Load 11 initial articles
          return {
            id: source.id,
            name: source.name,
            sub: source.description,
            logo: source.logo,
            url: source.url,
            category: source.category,
            news: data.articles.map((article) => ({
              id: article.id,
              title: article.title,
              desc: article.description || '',
              image: article.image_url || `https://picsum.photos/seed/${source.id}-${article.id}/400/250`,
              link: article.link,
              time: new Date(article.pub_date).toLocaleString('id-ID', { 
                day: 'numeric', 
                month: 'short', 
                year: 'numeric',
                hour: '2-digit',
                minute: '2-digit'
              }),
              pubDate: article.pub_date
            })),
            hasMore: data.count >= 11,
            skip: 11,
          };
        })
      );
      newsSources = results.filter(source => source.news.length > 0);
      
      // Initialize visible count and loading state for each source
      newsSources.forEach((source) => {
        visibleCount[source.id] = 11;
        loadingMore[source.id] = false;
      });
      
      // Prepare featured news from loaded articles
      featuredNews = results
        .flatMap((source) =>
          source.news.slice(0, 2).map((news) => ({
            ...news,
            sourceName: source.name,
            sourceLogo: source.logo || fallbackLogo,
          }))
        )
        .slice(0, 6)
        .map((news, idx) => ({
          ...news,
          bgColor: sliderColors[idx % sliderColors.length],
        }));
    } catch (error) {
      console.error('Error loading articles:', error);
    } finally {
      isLoading = false;
    }
  }

  // Load more articles for specific source
  async function handleShowMore(sourceId) {
    const source = newsSources.find(s => s.id === sourceId);
    if (!source || !source.hasMore || loadingMore[sourceId]) return;
    
    loadingMore[sourceId] = true;
    try {
      const data = await fetchArticlesBySource(sourceId, 11, source.skip);
      
      const newArticles = data.articles.map((article) => ({
        id: article.id,
        title: article.title,
        desc: article.description || '',
        image: article.image_url || `https://picsum.photos/seed/${sourceId}-${article.id}/400/250`,
        link: article.link,
        time: new Date(article.pub_date).toLocaleString('id-ID', { 
          day: 'numeric', 
          month: 'short', 
          year: 'numeric',
          hour: '2-digit',
          minute: '2-digit'
        }),
        pubDate: article.pub_date
      }));
      
      newsSources = newsSources.map(s => {
        if (s.id === sourceId) {
          return {
            ...s,
            news: [...s.news, ...newArticles],
            hasMore: data.count >= 11,
            skip: s.skip + data.count,
          };
        }
        return s;
      });
      
      visibleCount = { ...visibleCount, [sourceId]: visibleCount[sourceId] + 11 };
    } catch (error) {
      console.error('Error loading more articles:', error);
    } finally {
      loadingMore[sourceId] = false;
    }
  }

  // Scroll to source card when clicked in sidebar
  function scrollToSource(sourceId) {
    const element = document.getElementById(`source-${sourceId}`);
    if (element) {
      element.scrollIntoView({ 
        behavior: 'smooth', 
        block: 'start',
        inline: 'nearest'
      });
      // Close mobile sidebar after clicking
      if (window.innerWidth < 768) {
        isSidebarOpen = false;
      }
    }
  }

  // Prepare featured news
  featuredNews = [];

  // Auto-slide
  onMount(() => {
    loadInitialArticles();
    
    const timer = setInterval(() => {
      if (featuredNews.length > 0) {
        currentSlide = (currentSlide + 1) % featuredNews.length;
      }
    }, 5000);
    return () => clearInterval(timer);
  });

  function nextSlide() {
    currentSlide = (currentSlide + 1) % featuredNews.length;
  }

  function prevSlide() {
    currentSlide =
      (currentSlide - 1 + featuredNews.length) % featuredNews.length;
  }

  let filteredSources = $derived(newsSources.filter((source) =>
    source.name.toLowerCase().includes(searchQuery.toLowerCase())
  ));
</script>

<div class="min-h-screen {bodyBgColor} text-neutral overflow-hidden flex flex-col">
  <!-- NAVBAR -->
  <nav
    class="navbar px-6 border-b-2 border-black/15 shadow-[0_2px_8px_rgba(0,0,0,0.08)] fixed top-0 left-0 right-0 z-50 {bodyBgColor}"
  >
    <div class="navbar-start flex items-center gap-3">
      <div
        class="btn btn-square btn-primary border-2 border-black/20 shadow-[2px_2px_0_rgba(0,0,0,0.12)]"
      >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="20"
          height="20"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
        >
          <path d="M4 11a9 9 0 0 1 9 9" />
          <path d="M4 4a16 16 0 0 1 16 16" />
          <circle cx="5" cy="19" r="1" />
        </svg>
      </div>
      <div>
        <p class="text-xs font-semibold uppercase tracking-[0.2em]">Tilik</p>
        <h1 class="text-2xl font-black leading-tight tracking-tight">Feed</h1>
      </div>
    </div>

    <div class="navbar-end gap-2">
      <a 
        href="/admin"
        class="btn btn-sm btn-ghost"
        title="Admin Dashboard"
      >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="20"
          height="20"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
        >
          <path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z"></path>
          <circle cx="12" cy="12" r="3"></circle>
        </svg>
      </a>
      <button
        onclick={() => (isSidebarOpen = !isSidebarOpen)}
        class="btn btn-square btn-ghost border-2 border-neutral neo-hover"
        aria-label="Toggle sidebar"
      >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="24"
          height="24"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
        >
          <line x1="4" x2="20" y1="12" y2="12" />
          <line x1="4" x2="20" y1="6" y2="6" />
          <line x1="4" x2="20" y1="18" y2="18" />
        </svg>
      </button>
    </div>
  </nav>

  <div class="flex flex-1 relative overflow-hidden pt-20">
    <!-- MAIN FEED -->
    <main
      class="overflow-y-auto px-4 md:px-8 lg:px-12 xl:px-16 py-8 flex-1 md:flex-none {isSidebarOpen
        ? 'md:w-[calc(100%-280px)]'
        : 'md:w-full'}"
    >
      <!-- Loading State -->
      {#if isLoading}
        <div class="flex items-center justify-center min-h-[400px]">
          <div class="text-center">
            <span class="loading loading-spinner loading-lg"></span>
            <p class="mt-4 text-lg font-semibold">Loading articles...</p>
          </div>
        </div>
      {:else}
        <!-- SLIDER / CAROUSEL -->
        <div class="mx-auto w-full max-w-[1280px] mb-8">
          <div
            class="relative rounded-2xl border-2 border-black/15 overflow-hidden shadow-[4px_4px_0_rgba(0,0,0,0.1)] bg-base-200"
          >
            <!-- Slides -->
            <div class="relative h-[300px] md:h-[400px]">
              {#each featuredNews as news, idx}
                <div
                  class="absolute inset-0 transition-opacity duration-700 {idx ===
                  currentSlide
                    ? 'opacity-100'
                    : 'opacity-0'}"
                >
                  <div class="relative w-full h-full">
                    <!-- Colorful Background -->
                    <div class="absolute inset-0 {news.bgColor}"></div>

                    <!-- Background Image with Blend -->
                    <img
                      src={news.image}
                      alt="{news.title}"
                      loading="{idx === 0 ? 'eager' : 'lazy'}"
                      fetchpriority="{idx === 0 ? 'high' : 'auto'}"
                      width="1280"
                      height="400"
                      class="absolute inset-0 w-full h-full object-cover mix-blend-overlay opacity-60"
                    />

                    <!-- Dark Gradient for Text -->
                    <div
                      class="absolute inset-0 bg-gradient-to-t from-black/80 via-black/30 to-transparent"
                    ></div>

                    <!-- Content -->
                    <div
                      class="absolute bottom-0 left-0 right-0 p-6 md:p-8 text-white"
                    >
                      <div class="flex items-center gap-2 mb-3">
                        <img
                          src={news.sourceLogo}
                          alt="{news.sourceName} logo"
                          width="32"
                          height="32"
                          class="w-8 h-8 rounded-full border-2 border-white bg-white"
                        />
                        <span
                          class="text-xs font-bold uppercase tracking-wide"
                        >
                          {news.sourceName}
                        </span>
                        <span class="text-xs opacity-70">• {news.time}</span>
                      </div>
                      <h2
                        class="text-2xl md:text-3xl font-black leading-tight mb-2 drop-shadow-lg"
                      >
                        {news.title}
                      </h2>
                      <p
                        class="text-sm md:text-base opacity-90 line-clamp-2 max-w-3xl"
                      >
                        {news.desc}
                      </p>
                    </div>
                  </div>
                </div>
              {/each}
            </div>

            <!-- Navigation Buttons -->
          <button
            onclick={prevSlide}
            class="absolute left-4 top-1/2 -translate-y-1/2 btn btn-circle btn-primary border-2 border-neutral shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] hover:shadow-none hover:translate-x-[2px] hover:translate-y-[2px] z-10"
            aria-label="Previous slide"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="24"
              height="24"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
            >
              <path d="m15 18-6-6 6-6" />
            </svg>
          </button>
          <button
            onclick={nextSlide}
            class="absolute right-4 top-1/2 -translate-y-1/2 btn btn-circle btn-primary border-2 border-neutral shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] hover:shadow-none hover:translate-x-[2px] hover:translate-y-[2px] z-10"
            aria-label="Next slide"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="24"
              height="24"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
            >
              <path d="m9 18 6-6-6-6" />
            </svg>
          </button>

          <!-- Indicators -->
          <div
            class="absolute bottom-4 left-1/2 -translate-x-1/2 flex gap-2 z-10"
          >
            {#each featuredNews as _, idx}
              <button
                onclick={() => (currentSlide = idx)}
                class="h-2 rounded-full border border-neutral transition-all {idx ===
                currentSlide
                  ? 'w-8 bg-primary'
                  : 'w-2 bg-white/50 hover:bg-white/80'}"
                aria-label="Go to slide {idx + 1}"
              ></button>
            {/each}
          </div>
        </div>
      </div>

      <div
        class="mx-auto w-full max-w-[1280px] grid gap-5 grid-cols-[repeat(auto-fit,minmax(220px,1fr))]"
      >
        {#each newsSources as source, sourceIdx}
          {@const shown = visibleCount[source.id] ?? 11}
          {@const logoUrl = source.logo || fallbackLogo}
          <div
            id="source-{source.id}"
            class="card card-bordered border-2 border-black/15 bg-base-200 h-full min-h-0 shadow-[2px_2px_0_rgba(0,0,0,0.08)]"
          >
            <!-- Header -->
            <div
              class="px-3 py-3 sticky top-0 bg-base-200 border-b border-black/15"
            >
              <div class="flex items-center gap-2">
                <img
                  src={logoUrl}
                  alt="{source.name} logo"
                  width="48"
                  height="48"
                  class="w-12 h-12 object-cover"
                  loading="lazy"
                />
                <div class="min-w-0">
                  <h2 class="card-title leading-tight text-base">
                    {source.name}
                  </h2>
                  <p class="text-xs opacity-70 truncate mt-1">{source.sub}</p>
                </div>
              </div>
            </div>

            <!-- List Berita -->
            <div class="flex-1 overflow-y-auto px-3 py-4 space-y-4 bg-base-200">
              {#each source.news.slice(0, shown) as item, idx}
                <a
                  href={item.link}
                  target="_blank"
                  rel="noopener noreferrer"
                  class="group card card-compact border border-black/15 shadow-[1px_1px_0_rgba(0,0,0,0.08)] neo-hover {cardColors[
                    (idx + sourceIdx) % cardColors.length
                  ]} block no-underline hover:border-black/25 hover:shadow-[2px_2px_0_rgba(0,0,0,0.12)]"
                >
                  <div class="card-body gap-3 px-3 py-3">
                    <h3 class="font-bold text-base leading-tight group-hover:text-primary transition-colors">
                      {item.title}
                    </h3>

                    {#if item.image}
                      <figure
                        class="rounded-lg overflow-hidden border border-neutral shadow-inner"
                      >
                        <img
                          src={item.image}
                          alt="{item.title}"
                          loading="lazy"
                          width="640"
                          height="360"
                          class="w-full aspect-video object-cover"
                        />
                      </figure>
                    {/if}

                    <p class="text-sm leading-snug opacity-80 line-clamp-2">
                      {item.desc}
                    </p>

                    <div
                      class="flex justify-between items-center text-xs font-semibold"
                    >
                      <span class="uppercase tracking-tight opacity-70">
                        {item.time}
                      </span>
                      <span
                        class="opacity-70 group-hover:opacity-100 group-hover:text-primary transition-all"
                      >
                        Read →
                      </span>
                    </div>
                  </div>
                </a>
              {/each}
            </div>

            <div class="p-4 bg-base-200 border-t-2 border-neutral">
              {#if loadingMore[source.id]}
                <button
                  class="btn btn-primary btn-block border-2 border-neutral shadow-[var(--shadow-1)]"
                  disabled
                >
                  <span class="loading loading-spinner"></span>
                  Loading...
                </button>
              {:else if source.hasMore}
                <button
                  class="btn btn-primary btn-block border-2 border-neutral shadow-[var(--shadow-1)] neo-hover"
                  onclick={() => handleShowMore(source.id)}
                >
                  Load More
                </button>
              {:else}
                <button
                  class="btn btn-primary btn-block border-2 border-neutral shadow-[var(--shadow-1)]"
                  disabled
                >
                  All Caught Up
                </button>
              {/if}
            </div>
          </div>
        {/each}
      </div>
      {/if}
    </main>

    <!-- Desktop sidebar -->
    <aside
      class="{isSidebarOpen
        ? 'hidden md:flex'
        : 'hidden'} fixed top-16 right-0 min-h-[calc(100vh-64px)] max-h-[calc(100vh-64px)] w-[280px] bg-base-100 border-l-4 border-neutral shadow-[var(--shadow-1)] overflow-hidden"
    >
      <div class="py-6 px-4 flex flex-col h-full w-full gap-4">
        <div
          class="flex justify-between items-center border-b-4 border-neutral pb-3"
        >
          <span class="font-black tracking-tight uppercase text-sm">
            RSS Feed Sources
          </span>
        </div>

        <label
          class="input input-bordered input-lg flex items-center gap-2 shadow-[var(--shadow-1)] bg-base-200 border-2 border-neutral"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
          >
            <circle cx="11" cy="11" r="8" />
            <path d="m21 21-4.3-4.3" />
          </svg>
          <input
            type="text"
            class="grow text-sm placeholder:text-xs"
            placeholder="Cari sumber berita..."
            bind:value={searchQuery}
          />
        </label>

        <ul
          class="menu flex flex-col flex-nowrap flex-1 gap-1 w-full pr-1 max-h-[calc(100vh-200px)] overflow-y-auto"
        >
          {#each filteredSources as source (source.id)}
            <li>
              <button                onclick={() => scrollToSource(source.id)}                class="w-full justify-start gap-3 font-semibold px-3 py-2 rounded-lg hover:bg-base-200 hover:border hover:border-neutral hover:shadow-[4px_4px_0_#111]"
              >
                <img
                  src={source.logo || fallbackLogo}
                  alt={source.name}
                  class="w-6 h-6 rounded-md object-cover flex-shrink-0"
                />
                <span class="flex-1 text-left">{source.name}</span>
                <span
                  class="text-xs font-black tracking-tight opacity-60 group-hover:opacity-100"
                >
                  ›
                </span>
              </button>
            </li>
          {:else}
            <li class="text-center text-sm italic text-neutral/60">
              Sumber "{searchQuery}" tidak ditemukan
            </li>
          {/each}
        </ul>
      </div>
    </aside>

    <!-- Mobile drawer -->
    <aside
      class="md:hidden fixed top-0 right-0 h-full w-[260px] bg-base-100 shadow-[var(--shadow-1)] z-[60] transform transition-transform duration-300 ease-in-out border-l-4 border-neutral {isSidebarOpen
        ? 'translate-x-0'
        : 'translate-x-full'}"
    >
      <div class="py-6 px-4 flex flex-col h-full w-full gap-4">
        <div
          class="flex justify-between items-center border-b-4 border-neutral pb-3"
        >
          <span class="font-black tracking-tight uppercase text-sm">
            RSS Feed Sources
          </span>
          <button
            onclick={() => (isSidebarOpen = false)}
            class="btn btn-sm btn-square btn-ghost border-2 border-neutral neo-hover"
            aria-label="Close sidebar"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="18"
              height="18"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
            >
              <path d="M18 6 6 18" />
              <path d="m6 6 12 12" />
            </svg>
          </button>
        </div>

        <label
          class="input input-bordered input-lg flex items-center gap-2 shadow-[var(--shadow-1)] bg-base-200 border-2 border-neutral"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
          >
            <circle cx="11" cy="11" r="8" />
            <path d="m21 21-4.3-4.3" />
          </svg>
          <input
            type="text"
            class="grow text-sm placeholder:text-xs"
            placeholder="Cari sumber berita..."
            bind:value={searchQuery}
          />
        </label>

        <ul
          class="menu flex flex-col flex-nowrap flex-1 gap-1 w-full pr-1 max-h-[calc(100vh-200px)] overflow-y-auto"
        >
          {#each filteredSources as source (source.id)}
            <li>
              <button
                onclick={() => scrollToSource(source.id)}
                class="w-full justify-start gap-3 font-semibold px-3 py-2 rounded-lg hover:bg-base-200 hover:border hover:border-neutral hover:shadow-[4px_4px_0_#111]"
              >
                <img
                  src={source.logo || fallbackLogo}
                  alt={source.name}
                  class="w-6 h-6 rounded-md object-cover flex-shrink-0"
                />
                <span class="flex-1 text-left">{source.name}</span>
                <span
                  class="text-xs font-black tracking-tight opacity-60 group-hover:opacity-100"
                >
                  ›
                </span>
              </button>
            </li>
          {:else}
            <li class="text-center text-sm italic text-neutral/60">
              Sumber "{searchQuery}" tidak ditemukan
            </li>
          {/each}
        </ul>
      </div>
    </aside>

    {#if isSidebarOpen}
      <div
        class="md:hidden fixed inset-0 bg-black/20 backdrop-blur-[1px] z-[55]"
        onclick={() => (isSidebarOpen = false)}
        onkeydown={(e) => e.key === "Escape" && (isSidebarOpen = false)}
        role="button"
        tabindex="0"
      ></div>
    {/if}
  </div>
</div>

// src/App.jsx
import { useState, useEffect, useMemo } from "react";
import { Menu, X, Search, Rss, ChevronLeft, ChevronRight } from "lucide-react";
import { newsSources } from "./data";
import fallbackLogo from "./assets/logo-fallback.svg";

function App() {
  const [isSidebarOpen, setIsSidebarOpen] = useState(false);
  const [searchQuery, setSearchQuery] = useState("");
  const [visibleCount, setVisibleCount] = useState(() =>
    Object.fromEntries(newsSources.map((source) => [source.id, 5]))
  );
  const [currentSlide, setCurrentSlide] = useState(0);

  // Fungsi untuk shuffle array
  const shuffleArray = (array) => {
    const shuffled = [...array];
    for (let i = shuffled.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
    }
    return shuffled;
  };

  // Ambil berita untuk slider dari berbagai sumber
  const allSliderColors = [
    "bg-gradient-to-br from-pink-400 via-purple-400 to-indigo-500",
    "bg-gradient-to-br from-yellow-400 via-orange-400 to-red-500",
    "bg-gradient-to-br from-green-400 via-emerald-400 to-teal-500",
    "bg-gradient-to-br from-blue-400 via-cyan-400 to-sky-500",
    "bg-gradient-to-br from-violet-400 via-fuchsia-400 to-pink-500",
    "bg-gradient-to-br from-amber-400 via-lime-400 to-green-500",
    "bg-gradient-to-br from-red-400 via-rose-400 to-pink-500",
    "bg-gradient-to-br from-cyan-400 via-blue-400 to-indigo-500",
    "bg-gradient-to-br from-lime-400 via-green-400 to-emerald-500",
    "bg-gradient-to-br from-orange-400 via-amber-400 to-yellow-500",
    "bg-gradient-to-br from-fuchsia-400 via-purple-400 to-violet-500",
    "bg-gradient-to-br from-teal-400 via-cyan-400 to-blue-500",
  ];

  const allCardColors = [
    "bg-pink-100",
    "bg-yellow-100",
    "bg-green-100",
    "bg-blue-100",
    "bg-purple-100",
    "bg-orange-100",
    "bg-teal-100",
    "bg-indigo-100",
    "bg-rose-100",
    "bg-lime-100",
    "bg-cyan-100",
    "bg-amber-100",
    "bg-emerald-100",
    "bg-sky-100",
    "bg-violet-100",
    "bg-fuchsia-100",
    "bg-red-100",
    "bg-slate-100",
    "bg-stone-100",
    "bg-zinc-100",
  ];

  // Shuffle warna sekali saat component mount
  const sliderColors = useMemo(() => shuffleArray(allSliderColors), []);
  const cardColors = useMemo(() => shuffleArray(allCardColors), []);

  const featuredNews = newsSources.flatMap((source) =>
    source.news.slice(0, 2).map((news) => ({
      ...news,
      sourceName: source.name,
      sourceLogo: source.logo || fallbackLogo,
    }))
  ).slice(0, 6).map((news, idx) => ({
    ...news,
    bgColor: sliderColors[idx % sliderColors.length],
  })); // Ambil 6 berita featured

  // Auto-slide setiap 5 detik
  useEffect(() => {
    const timer = setInterval(() => {
      setCurrentSlide((prev) => (prev + 1) % featuredNews.length);
    }, 5000);
    return () => clearInterval(timer);
  }, [featuredNews.length]);

  const nextSlide = () => {
    setCurrentSlide((prev) => (prev + 1) % featuredNews.length);
  };

  const prevSlide = () => {
    setCurrentSlide((prev) => (prev - 1 + featuredNews.length) % featuredNews.length);
  };

  const filteredSources = newsSources.filter((source) =>
    source.name.toLowerCase().includes(searchQuery.toLowerCase())
  );

  const handleShowMore = (sourceId, totalNews) => {
    setVisibleCount((prev) => {
      const current = prev[sourceId] ?? 5;
      const next = Math.min(current + 5, totalNews);
      return { ...prev, [sourceId]: next };
    });
  };

  const SidebarContent = ({ showClose = false }) => (
    <div className="py-6 px-4 flex flex-col h-full w-full gap-4">
      <div className="flex justify-between items-center border-b-4 border-neutral pb-3">
        <span className="font-black tracking-tight uppercase text-sm">
          RSS Feed Sources
        </span>
        {showClose && (
          <button
            onClick={() => setIsSidebarOpen(false)}
            className="btn btn-sm btn-square btn-ghost border-2 border-neutral neo-hover"
            aria-label="Close sidebar"
          >
            <X size={18} />
          </button>
        )}
      </div>

      <label className="input input-bordered input-lg flex items-center gap-2 shadow-[var(--shadow-1)] bg-base-200 border-2 border-neutral">
        <Search size={16} />
        <input
          type="text"
          className="grow text-sm placeholder:text-xs"
          placeholder="Cari sumber berita..."
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
        />
      </label>

      <ul className="menu flex flex-col flex-nowrap flex-1 gap-1 w-full pr-1 max-h-[calc(100vh-200px)] overflow-y-auto">
        {filteredSources.map((source) => (
          <li key={source.id}>
            <button className="w-full justify-between font-semibold px-3 py-2 rounded-lg hover:bg-base-200 hover:border hover:border-neutral hover:shadow-[4px_4px_0_#111]">
              {source.name}
              <span className="text-xs font-black tracking-tight opacity-60 group-hover:opacity-100">
                ›
              </span>
            </button>
          </li>
        ))}
        {filteredSources.length === 0 && (
          <li className="text-center text-sm italic text-neutral/60">
            Sumber "{searchQuery}" tidak ditemukan
          </li>
        )}
      </ul>
    </div>
  );

  return (
    <div className="min-h-screen bg-base-100 text-neutral overflow-hidden flex flex-col">
      {/* --- NAVBAR --- */}
      <nav className="navbar px-6 border-b-4 border-neutral shadow-[var(--shadow-1)] fixed top-0 left-0 right-0 z-50 bg-base-100">
        <div className="navbar-start flex items-center gap-3">
          <div className="btn btn-square btn-primary border-2 border-neutral shadow-[var(--shadow-1)]">
            <Rss size={20} />
          </div>
          <div>
            <p className="text-xs font-semibold uppercase tracking-[0.2em]">
              Tilik
            </p>
            <h1 className="text-2xl font-black leading-tight tracking-tight">
              Feed
            </h1>
          </div>
        </div>

        <div className="navbar-end">
          <button
            onClick={() => setIsSidebarOpen((prev) => !prev)}
            className="btn btn-square btn-ghost border-2 border-neutral neo-hover"
            aria-label="Toggle sidebar"
          >
            <Menu size={24} />
          </button>
        </div>
      </nav>

      <div className="flex flex-1 relative overflow-hidden pt-20">
        {/* --- MAIN FEED --- */}
        <main
          className={`overflow-y-auto px-4 md:px-8 lg:px-12 xl:px-16 py-8 flex-1 md:flex-none ${
            isSidebarOpen ? "md:w-[calc(100%-280px)]" : "md:w-full"
          }`}
        >
          {/* --- SLIDER / CAROUSEL --- */}
          <div className="mx-auto w-full max-w-[1280px] mb-8">
            <div className="relative rounded-2xl border-4 border-neutral overflow-hidden shadow-[8px_8px_0px_0px_rgba(0,0,0,1)] bg-base-200">
              {/* Slides */}
              <div className="relative h-[300px] md:h-[400px]">
                {featuredNews.map((news, idx) => (
                  <div
                    key={news.id}
                    className={`absolute inset-0 transition-opacity duration-700 ${
                      idx === currentSlide ? "opacity-100" : "opacity-0"
                    }`}
                  >
                    <div className="relative w-full h-full">
                      {/* Colorful Background */}
                      <div className={`absolute inset-0 ${news.bgColor}`} />
                      
                      {/* Background Image with Blend */}
                      <img
                        src={news.image}
                        alt=""
                        className="absolute inset-0 w-full h-full object-cover mix-blend-overlay opacity-60"
                      />
                      
                      {/* Dark Gradient for Text */}
                      <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/30 to-transparent" />
                      
                      {/* Content */}
                      <div className="absolute bottom-0 left-0 right-0 p-6 md:p-8 text-white">
                        <div className="flex items-center gap-2 mb-3">
                          <img
                            src={news.sourceLogo}
                            alt={news.sourceName}
                            className="w-8 h-8 rounded-full border-2 border-white bg-white"
                          />
                          <span className="text-xs font-bold uppercase tracking-wide">
                            {news.sourceName}
                          </span>
                          <span className="text-xs opacity-70">• {news.time}</span>
                        </div>
                        <h2 className="text-2xl md:text-3xl font-black leading-tight mb-2 drop-shadow-lg">
                          {news.title}
                        </h2>
                        <p className="text-sm md:text-base opacity-90 line-clamp-2 max-w-3xl">
                          {news.desc}
                        </p>
                      </div>
                    </div>
                  </div>
                ))}
              </div>

              {/* Navigation Buttons */}
              <button
                onClick={prevSlide}
                className="absolute left-4 top-1/2 -translate-y-1/2 btn btn-circle btn-primary border-2 border-neutral shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] hover:shadow-none hover:translate-x-[2px] hover:translate-y-[2px] z-10"
                aria-label="Previous slide"
              >
                <ChevronLeft size={24} />
              </button>
              <button
                onClick={nextSlide}
                className="absolute right-4 top-1/2 -translate-y-1/2 btn btn-circle btn-primary border-2 border-neutral shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] hover:shadow-none hover:translate-x-[2px] hover:translate-y-[2px] z-10"
                aria-label="Next slide"
              >
                <ChevronRight size={24} />
              </button>

              {/* Indicators */}
              <div className="absolute bottom-4 left-1/2 -translate-x-1/2 flex gap-2 z-10">
                {featuredNews.map((_, idx) => (
                  <button
                    key={idx}
                    onClick={() => setCurrentSlide(idx)}
                    className={`h-2 rounded-full border border-neutral transition-all ${
                      idx === currentSlide
                        ? "w-8 bg-primary"
                        : "w-2 bg-white/50 hover:bg-white/80"
                    }`}
                    aria-label={`Go to slide ${idx + 1}`}
                  />
                ))}
              </div>
            </div>
          </div>

          <div className="mx-auto w-full max-w-[1280px] grid gap-5 grid-cols-[repeat(auto-fit,minmax(220px,1fr))]">
            {newsSources.map((source, sourceIdx) => {
              const shown = visibleCount[source.id] ?? 5;
              const canShowMore = shown < source.news.length;
              const logoUrl = source.logo || fallbackLogo;
              return (
                <div
                  key={source.id}
                  className="card card-bordered border-2 border-neutral bg-base-200 h-full min-h-0 shadow-[var(--shadow-1)]"
                >
                  {/* Header */}
                  <div className="px-3 py-3 sticky top-0 bg-base-200 border-b-2 border-neutral">
                    <div className="flex items-center gap-2">
                      <img
                        src={logoUrl}
                        alt={source.name}
                        className="w-12 h-12 object-cover"
                        loading="lazy"
                      />
                      <div className="min-w-0">
                        <h2 className="card-title leading-tight text-base">
                          {source.name}
                        </h2>
                        <p className="text-xs opacity-70 truncate mt-1">
                          {source.sub}
                        </p>
                      </div>
                    </div>
                  </div>

                  {/* List Berita */}
                  <div className="flex-1 overflow-y-auto px-3 py-4 space-y-4 bg-base-100">
                    {source.news.slice(0, shown).map((item, idx) => (
                      <article
                        key={item.id}
                        className={`group card card-compact border border-neutral shadow-[var(--shadow-1)] neo-hover ${
                          cardColors[(idx + sourceIdx) % cardColors.length]
                        }`}
                      >
                        <div className="card-body gap-3 px-3 py-3">
                          <h3 className="font-bold text-base leading-tight">
                            {item.title}
                          </h3>

                          {item.image && (
                            <figure className="rounded-lg overflow-hidden border border-neutral shadow-inner">
                              <img
                                src={item.image}
                                alt=""
                                className="w-full aspect-video object-cover"
                              />
                            </figure>
                          )}

                          <p className="text-sm leading-snug opacity-80 line-clamp-2">
                            {item.desc}
                          </p>

                          <div className="flex justify-between items-center text-xs font-semibold">
                            <span className="uppercase tracking-tight opacity-70">
                              {item.time}
                            </span>
                            <span className="opacity-0 group-hover:opacity-100 transition-opacity">
                              Read →
                            </span>
                          </div>
                        </div>
                      </article>
                    ))}
                  </div>

                  <div className="p-4 bg-base-200 border-t-2 border-neutral">
                    <button
                      className="btn btn-primary btn-block border-2 border-neutral shadow-[var(--shadow-1)] neo-hover"
                      onClick={() => handleShowMore(source.id, source.news.length)}
                      disabled={!canShowMore}
                    >
                      {canShowMore ? "Show More" : "All Caught Up"}
                    </button>
                  </div>
                </div>
              );
            })}
          </div>
        </main>

        {/* Desktop sidebar */}
        <aside
          className={`${isSidebarOpen ? "hidden md:flex" : "hidden"} fixed top-16 right-0 min-h-[calc(100vh-64px)] max-h-[calc(100vh-64px)] w-[280px] bg-base-100 border-l-4 border-neutral shadow-[var(--shadow-1)] overflow-hidden`}
        >
          <SidebarContent />
        </aside>

        {/* Mobile drawer */}
        <aside
          className={`md:hidden fixed top-0 right-0 h-full w-[260px] bg-base-100 shadow-[var(--shadow-1)] z-[60] transform transition-transform duration-300 ease-in-out border-l-4 border-neutral ${
            isSidebarOpen ? "translate-x-0" : "translate-x-full"
          }`}
        >
          <SidebarContent showClose />
        </aside>

        {isSidebarOpen && (
          <div
            className="md:hidden fixed inset-0 bg-black/20 backdrop-blur-[1px] z-[55]"
            onClick={() => setIsSidebarOpen(false)}
          />
        )}
      </div>
    </div>
  );
}

export default App;
